FROM node:20-alpine

WORKDIR /app

# We copy root files and install workspace dependencies
COPY package.json ./

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3001

CMD ["npm", "run", "dev"]
